### ISSUE TITLE
feat: deb support

### ISSUE THREAD

**Issue by EnableAsync** [api7/apisix-build-tools#62]
#### Background
For the convenience of Ubuntu/Debian users, we need to support deb.

#### TODO
Based on the current situation, the following points need to be completed:
- [x] deb for APISIX
- [x] deb for APISIX Dashboard
- [x] deb for APISIX's OpenResty

And test for them:

- [x] Test for APISIX deb
- [x] Test for APISIX Dashboard deb
- [x] Test for APISIX's OpenResty deb

**Comment by imjoey** [comment]
@EnableAsync Hi, I think we can mark deb for APISIX Dashboard as completed, with only APISIX's OpenResty left. Thank you very much for your contribution. 😄

**Comment by Kushal-kothari** [comment]
Can anyone help me with this config error whenever I am making changes with addition of modules!
```T
adding module in /tmp/tmp.Foa88QVBrc/openresty-1.19.3.2/../lua-var-nginx-module
 + ngx_http_lua_var_module was configured
adding module in /tmp/tmp.Foa88QVBrc/openresty-1.19.3.2/../lua_resty_maxminddb
./configure: error: no /tmp/tmp.Foa88QVBrc/openresty-1.19.3.2/../lua_resty_maxminddb/config was found
ERROR: failed to run command: sh ./configure --prefix=/usr/local/openresty/nginx \...
```
[Detail error log](https://github.com/Kushal-kothari/apisix-build-tools/runs/3595012707?check_suite_focus=true) of the error(more detail)

I think I am not able to update the configure script to invoke "sh" explicitly for nginx's ./configure script.
[The commit/changes ](https://github.com/Kushal-kothari/apisix-build-tools/commit/2081016751f714e4049e5274e6cee0a438afeffc)
